export interface Company {
  id: string;
  name: string;
  domain: string;
  category: string;
  description: string;
  founded: number;
  headquarters: string;
  employees: string;
  pricing: 'Free' | 'Freemium' | 'Paid';
  website: string;
}

export const companies: Company[] = [
  {
    id: 'slack',
    name: 'Slack',
    domain: 'slack.com',
    category: 'Team Communication',
    description: 'Channel-based messaging platform for modern team collaboration.',
    founded: 2009,
    headquarters: 'San Francisco, CA',
    employees: '2,500+',
    pricing: 'Freemium',
    website: 'https://slack.com',
  },
  {
    id: 'notion',
    name: 'Notion',
    domain: 'notion.so',
    category: 'Productivity',
    description: 'All-in-one workspace for notes, tasks, wikis, and databases.',
    founded: 2013,
    headquarters: 'San Francisco, CA',
    employees: '600+',
    pricing: 'Freemium',
    website: 'https://notion.so',
  },
  {
    id: 'figma',
    name: 'Figma',
    domain: 'figma.com',
    category: 'Design',
    description: 'Collaborative interface design tool that runs in the browser.',
    founded: 2012,
    headquarters: 'San Francisco, CA',
    employees: '1,300+',
    pricing: 'Freemium',
    website: 'https://figma.com',
  },
  {
    id: 'stripe',
    name: 'Stripe',
    domain: 'stripe.com',
    category: 'Payments',
    description: 'Online payment processing for internet businesses of every size.',
    founded: 2010,
    headquarters: 'San Francisco, CA',
    employees: '7,000+',
    pricing: 'Paid',
    website: 'https://stripe.com',
  },
  {
    id: 'shopify',
    name: 'Shopify',
    domain: 'shopify.com',
    category: 'E-commerce',
    description: 'Commerce platform that lets anyone start, run, and grow a business.',
    founded: 2006,
    headquarters: 'Ottawa, Canada',
    employees: '10,000+',
    pricing: 'Paid',
    website: 'https://shopify.com',
  },
  {
    id: 'hubspot',
    name: 'HubSpot',
    domain: 'hubspot.com',
    category: 'CRM',
    description: 'Inbound marketing, sales, and service software platform.',
    founded: 2006,
    headquarters: 'Cambridge, MA',
    employees: '7,000+',
    pricing: 'Freemium',
    website: 'https://hubspot.com',
  },
  {
    id: 'salesforce',
    name: 'Salesforce',
    domain: 'salesforce.com',
    category: 'CRM',
    description: 'Cloud-based customer relationship management platform.',
    founded: 1999,
    headquarters: 'San Francisco, CA',
    employees: '79,000+',
    pricing: 'Paid',
    website: 'https://salesforce.com',
  },
  {
    id: 'zoom',
    name: 'Zoom',
    domain: 'zoom.us',
    category: 'Video Conferencing',
    description: 'Cloud-based video communications and collaboration platform.',
    founded: 2011,
    headquarters: 'San Jose, CA',
    employees: '7,000+',
    pricing: 'Freemium',
    website: 'https://zoom.us',
  },
  {
    id: 'asana',
    name: 'Asana',
    domain: 'asana.com',
    category: 'Project Management',
    description: 'Work management platform for teams to coordinate and track projects.',
    founded: 2008,
    headquarters: 'San Francisco, CA',
    employees: '1,800+',
    pricing: 'Freemium',
    website: 'https://asana.com',
  },
  {
    id: 'github',
    name: 'GitHub',
    domain: 'github.com',
    category: 'Developer Tools',
    description: 'Code hosting, version control, and collaboration platform for developers.',
    founded: 2008,
    headquarters: 'San Francisco, CA',
    employees: '4,000+',
    pricing: 'Freemium',
    website: 'https://github.com',
  },
  {
    id: 'datadog',
    name: 'Datadog',
    domain: 'datadoghq.com',
    category: 'Observability',
    description: 'Monitoring and analytics platform for cloud-scale applications.',
    founded: 2010,
    headquarters: 'New York, NY',
    employees: '5,000+',
    pricing: 'Paid',
    website: 'https://datadoghq.com',
  },
  {
    id: 'mailchimp',
    name: 'Mailchimp',
    domain: 'mailchimp.com',
    category: 'Email Marketing',
    description: 'All-in-one marketing platform built for small businesses.',
    founded: 2001,
    headquarters: 'Atlanta, GA',
    employees: '1,200+',
    pricing: 'Freemium',
    website: 'https://mailchimp.com',
  },
];
